"""Long-task plumbing shared by every training/eval run (plan section 10):
atomic status.json, the task lock, and STOP-file handling.

The STOP file is the ONLY voluntary stop. Signal handling (a graceful
Ctrl+C) used to exist and was removed on purpose: it was a second,
rarely-exercised shutdown path and it produced several real bugs
(handlers restored before the final save, an impatient second Ctrl+C
discarding it, no escape hatch). One path that always runs beats two,
one of which rots -- see Candea & Fox, "Crash-Only Software" (HotOS 2003).
Everything that is not a STOP file is now a hard failure, and the
periodic checkpoint is what bounds its cost.

Each task lives in compare_lab/runs/<task_name>/ with:
  - status.json : machine-readable progress, rewritten atomically (temp+rename)
                  at most every ~30s (and always on state changes).
  - <task>.log  : full text log (the training script also prints a tqdm bar to
                  its own terminal window).
  - STOP        : if this file appears, the task saves a checkpoint and exits
                  with state "paused" (so it can be stopped from the phone).

status.json fields mirror the plan: task, model, state, pid, step/total,
percent, tokens/total, recent train loss, last val loss, tokens/s, elapsed,
eta_seconds, eta_clock, last checkpoint (step + time), updated_at, error.
"""

import json
import os
import time
from pathlib import Path

RUNS_DIR = Path(__file__).resolve().parent.parent / "runs"


def task_dir(task_name: str) -> Path:
    d = RUNS_DIR / task_name
    d.mkdir(parents=True, exist_ok=True)
    return d


def atomic_write_json(path: Path, obj, retries: int = 5) -> None:
    """Temp file + rename, with a retry and a non-fatal give-up.

    On Windows the rename fails with PermissionError while any process holds a
    handle on the destination (see checkpoint._replace_with_retry). status.json
    is rewritten every ~30s for hours and is read from outside while training
    runs, so a transient clash is likely -- and losing one progress update must
    never take down a multi-hour run."""
    path = Path(path)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(json.dumps(obj, indent=2))
    for i in range(retries):
        try:
            tmp.replace(path)
            return
        except PermissionError:
            if i == retries - 1:
                print(f"warning: could not update {path.name} (file busy); continuing")
                return
            time.sleep(0.2 * (i + 1))


def _process_alive(pid: int, create_time: float | None) -> bool | None:
    """True/False if we can tell, None if we cannot.

    PIDs get recycled -- aggressively on Windows, and especially across a reboot
    -- so pid_exists() alone would mistake an unrelated new process for the old
    owner and refuse a perfectly legitimate resume. psutil's own docs say
    Process.is_running() must be preferred over pid_exists(p.pid) for exactly
    this reason, so we also match the process start time."""
    try:
        import psutil
        if not psutil.pid_exists(pid):
            return False
        if create_time is None:
            return True  # old-format lock: no start time to compare
        try:
            return abs(psutil.Process(pid).create_time() - create_time) < 1.0
        except psutil.NoSuchProcess:
            return False
        except psutil.AccessDenied:
            return None
    except Exception:
        return None


def acquire_lock(task_name: str) -> Path | None:
    """Refuse to run two processes for the same task.

    Nothing coordinates writes to the shared batch-hash registry, so two
    concurrent runs of the same task append interleaved duplicate lines and
    corrupt it permanently: the index stops matching the batch, and the damage
    only surfaces hours later when another architecture verifies against it and
    reports a bogus "config drift". The registry can only be regenerated by
    retraining from scratch, so this is worth a hard stop.

    Created with O_CREAT|O_EXCL so two processes racing to start cannot both win
    (a plain exists()-then-write has a window where both pass). Fails CLOSED: if
    we cannot determine whether the owner is alive, we refuse rather than steal
    the lock."""
    lock = task_dir(task_name) / "LOCK"
    me = {"pid": os.getpid()}
    try:
        import psutil
        me["create_time"] = psutil.Process().create_time()
    except Exception:
        pass

    for _ in range(2):
        try:
            fd = os.open(lock, os.O_CREAT | os.O_EXCL | os.O_WRONLY)
            with os.fdopen(fd, "w") as f:
                json.dump(me, f)
            return lock
        except FileExistsError:
            pass

        owner = {}
        try:
            owner = json.loads(lock.read_text())
        except (json.JSONDecodeError, OSError):
            try:  # tolerate the old plain-PID format
                owner = {"pid": int(lock.read_text().strip())}
            except (ValueError, OSError):
                owner = {}

        pid = owner.get("pid")
        if pid == os.getpid():
            return lock  # already ours
        alive = _process_alive(pid, owner.get("create_time")) if pid else False
        if alive is not False:
            detail = "still running" if alive else "cannot be verified"
            raise RuntimeError(
                f"task {task_name!r} is locked by PID {pid} ({detail}; lock: {lock}). "
                f"Running two processes for the same task would corrupt the batch-hash "
                f"registry. Stop the other process, or delete the lock file if you are "
                f"certain it is stale.")
        print(f"note: taking over stale lock from dead PID {pid}")
        try:
            lock.unlink()
        except OSError:
            pass
    raise RuntimeError(f"could not acquire the lock for {task_name!r} ({lock})")


def release_lock(lock: Path | None) -> None:
    if lock is None or not lock.exists():
        return
    try:
        owner = json.loads(lock.read_text())
        if owner.get("pid") == os.getpid():
            lock.unlink()
    except (json.JSONDecodeError, OSError):
        pass


def stop_requested(task_name: str) -> bool:
    return (task_dir(task_name) / "STOP").exists()


def clear_stop(task_name: str) -> None:
    stop = task_dir(task_name) / "STOP"
    if stop.exists():
        stop.unlink()


def mark_error(task_name: str, message: str) -> None:
    """Record a crash in an existing status.json as state="error" with the
    message. Needed because an exception escapes before StatusWriter can flag
    it, which would otherwise leave the task reading "running" forever -- from
    the phone you would only see it go stale, with no idea why."""
    path = task_dir(task_name) / "status.json"
    state = {}
    if path.exists():
        try:
            state = json.loads(path.read_text())
        except json.JSONDecodeError:
            state = {}
    state.update({"task": task_name, "state": "error", "error": message[:2000],
                  "updated_at": time.strftime("%Y-%m-%d %H:%M:%S")})
    atomic_write_json(path, state)


class StatusWriter:
    """Throttled, atomic status.json writer with ETA bookkeeping."""

    def __init__(self, task_name: str, model: str, total_steps: int, total_tokens: int,
                 min_interval: float = 30.0, active_seconds_before: float = 0.0):
        """active_seconds_before seeds the cumulative "actual work time" counter
        from a resumed checkpoint, so a pause (no process running) never counts
        towards it -- only wall-clock time while a training process is actually
        alive does. See active_training_seconds vs elapsed_seconds below."""
        self.task_name = task_name
        self.dir = task_dir(task_name)
        self.path = self.dir / "status.json"
        self.min_interval = min_interval
        self.start_time = time.time()
        self._active_before = active_seconds_before
        self._last_write = 0.0
        self._state = {
            "task": task_name, "model": model, "state": "running", "pid": os.getpid(),
            "step": 0, "total_steps": total_steps, "percent": 0.0,
            "tokens": 0, "total_tokens": total_tokens,
            "train_loss": None, "val_loss": None, "tokens_per_sec": None,
            # elapsed_seconds: wall time since THIS process started (resets on
            # every resume -- useful to see "how long has the current window
            # been running", not total work).
            "elapsed_seconds": 0.0,
            # active_training_seconds: cumulative wall time across ALL resumes
            # that a training process was actually alive -- pauses are never
            # counted because no process runs (and therefore ticks this) during
            # a pause. This is the "solo tiempo de trabajo" figure.
            "active_training_seconds": round(active_seconds_before, 1),
            "eta_seconds": None, "eta_clock": None,
            "last_ckpt_step": None, "last_ckpt_time": None,
            "updated_at": None, "error": None,
        }

    @property
    def active_seconds(self) -> float:
        """Cumulative actual work time so far (this segment + prior resumes)."""
        return self._active_before + (time.time() - self.start_time)

    def update(self, step: int, tokens: int, train_loss=None, val_loss=None,
               tokens_per_sec=None, last_ckpt_step=None, force: bool = False) -> None:
        s = self._state
        s["step"] = step
        s["tokens"] = tokens
        if s["total_steps"]:
            s["percent"] = round(100.0 * step / s["total_steps"], 2)
        if train_loss is not None:
            s["train_loss"] = round(float(train_loss), 4)
        if val_loss is not None:
            s["val_loss"] = round(float(val_loss), 4)
        if tokens_per_sec is not None:
            s["tokens_per_sec"] = round(float(tokens_per_sec), 1)
        if last_ckpt_step is not None:
            s["last_ckpt_step"] = last_ckpt_step
            s["last_ckpt_time"] = time.strftime("%Y-%m-%d %H:%M:%S")
        s["elapsed_seconds"] = round(time.time() - self.start_time, 1)
        s["active_training_seconds"] = round(self.active_seconds, 1)
        if tokens_per_sec and s["total_tokens"]:
            remaining = max(0, s["total_tokens"] - tokens)
            eta = remaining / max(1e-9, tokens_per_sec)
            s["eta_seconds"] = round(eta, 1)
            s["eta_clock"] = time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(time.time() + eta))
        self._maybe_write(force)

    def _maybe_write(self, force: bool) -> None:
        now = time.time()
        if force or (now - self._last_write) >= self.min_interval:
            self._state["updated_at"] = time.strftime("%Y-%m-%d %H:%M:%S")
            atomic_write_json(self.path, self._state)
            self._last_write = now

    def set_state(self, state: str, error: str | None = None) -> None:
        self._state["state"] = state
        if error is not None:
            self._state["error"] = error
        self._maybe_write(force=True)

    def finished(self) -> None:
        self.set_state("finished")

    def paused(self) -> None:
        self.set_state("paused")

    def error(self, msg: str) -> None:
        self.set_state("error", error=msg)
